services:
  helix-mysql:
    image: mysql:latest
    container_name: helix-mysql
    hostname: helix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-helix}
      MYSQL_USER: ${MYSQL_USER:-helix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-helix}
    volumes:
      - helix_mysql_data:/var/lib/mysql
    restart: unless-stopped

  vault-mysql:
    image: mysql:latest
    container_name: vault-mysql
    hostname: vault-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${VAULT_MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${VAULT_MYSQL_DATABASE:-vault}
      MYSQL_USER: ${VAULT_MYSQL_USER:-vault}
      MYSQL_PASSWORD: ${VAULT_MYSQL_PASSWORD:-vault}
    volumes:
      - vault_mysql_data:/var/lib/mysql
    restart: unless-stopped

  helix-mysql-exporter:
    image: prom/mysqld-exporter
    container_name: helix-mysql-exporter
    hostname: helix-mysql-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporter_password@tcp(helix-mysql:3306)/
    ports:
      - '9104:9104'
    volumes:
      - ./configs/helix-mysql.cnf:/etc/.my.cnf
    command:
      - --config.my-cnf=/etc/.my.cnf
      - --mysqld.address=helix-mysql:3306
      - --collect.global_status
      - --collect.global_variables

  vault-mysql-exporter:
    image: prom/mysqld-exporter
    container_name: vault-mysql-exporter
    hostname: vault-mysql-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporter_password@tcp(vault-mysql:3306)/
    ports:
      - '9105:9104'
    volumes:
      - ./configs/vault-mysql.cnf:/etc/.my.cnf
    command:
      - --config.my-cnf=/etc/.my.cnf
      - --mysqld.address=vault-mysql:3306
      - --collect.global_status
      - --collect.global_variables
