---
kubernetes:
  children:
      master:
        hosts:
          "master-1":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.100"
          "master-2":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.101"
          "master-3":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.102"
      worker:
        hosts:
          "worker-1":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.150"
          "worker-2":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.151"
          "worker-3":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.152"
          "worker-4":
            ansible_user: "sinless777"
            ansible_host: "192.168.86.153"
