---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-dns
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./Kubernetes/apps/network/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: helix-ai-sh-1
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
