import Background from '../components/background'
import './global.css'
import { StyledComponentsRegistry } from './registry'

export const metadata = {
  title: 'Helix Ai',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Background $image="/images/helix/Background.png" />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
