---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  ANSIBLE_VARS_ENABLED: 'host_group_vars'
  ANSIBLE_LOCALHOST_WARNING: 'False'
  ANSIBLE_INVENTORY_UNPARSED_WARNING: 'False'

vars:
  ANSIBLE_LINT_FILE: '{{.ANSIBLE_DIR}}/.ansible-lint'
  ANSIBLE_INVENTORY_FILE: '{{.ANSIBLE_DIR}}/inventory/hosts.yaml'
  ANSIBLE_REQUIREMENTS_FILE: '{{.ROOT_DIR}}/requirements.yaml'
  ANSIBLE_PIP_REQUIREMENTS_FILE: '{{.ROOT_DIR}}/requirements.txt'

tasks:
  deps:
    desc: Set up Ansible dependencies
    cmds:
      - python3 -m pip install --upgrade --requirement "{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}"
      - ansible-galaxy install --role-file "{{.ANSIBLE_REQUIREMENTS_FILE}}" {{if eq .force "true"}}--force{{end}}
    preconditions:
      - {
          msg: 'Missing Ansible requirements file',
          sh: 'test -f {{.ANSIBLE_REQUIREMENTS_FILE}}',
        }
      - {
          msg: 'Missing Pip requirements file',
          sh: 'test -f {{.ANSIBLE_PIP_REQUIREMENTS_FILE}}',
        }
    sources:
      - '{{.ANSIBLE_REQUIREMENTS_FILE}}'
      - '{{.ANSIBLE_PIP_REQUIREMENTS_FILE}}'
    vars:
      force: '{{.force | default "true"}}'

  run:
    desc: Run an Ansible playbook for configuring a cluster
    summary: |
      Args:
        playbook: Playbook to run (required)
    prompt: Run Ansible playbook '{{.playbook}}'... continue?
    deps: ['deps']
    cmds:
      - 'ansible-playbook --inventory {{.ANSIBLE_INVENTORY_FILE}} {{.ANSIBLE_DIR}}/playbooks/{{.playbook}}.yaml {{.CLI_ARGS}}'
    requires:
      vars: ['playbook']
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  list:
    desc: List all the hosts
    deps: ['deps']
    cmd: 'ansible {{.group}} --inventory {{.ANSIBLE_INVENTORY_FILE}} --list-hosts'
    requires:
      vars: ['group']
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  ping:
    desc: Ping all the hosts
    deps: ['deps']
    cmd: "ansible {{.group}} --inventory {{.ANSIBLE_INVENTORY_FILE}} --one-line -m 'ping'"
    requires:
      vars: ['group']
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  uptime:
    desc: Uptime of all the hosts
    deps: ['deps']
    cmd: "ansible kubernetes --inventory {{.ANSIBLE_INVENTORY_FILE}} --one-line -a 'uptime'"
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  lint:
    desc: Lint Ansible
    deps: ['deps']
    cmd: 'ansible-lint --config-file {{.ANSIBLE_LINT_FILE}} {{.ANSIBLE_DIR}}/**/*.yaml'
    preconditions:
      - {
          msg: 'Missing Ansible lint file',
          sh: 'test -f {{.ANSIBLE_LINT_FILE}}',
        }

  install-docker:
    desc: Install Docker
    deps: ['deps']
    cmd: 'ansible-playbook --inventory {{.ANSIBLE_INVENTORY_FILE}} {{.ANSIBLE_DIR}}/playbooks/docker-swarm-cluster.yaml'
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  install-kubernetes:
    desc: Install Kubernetes
    deps: ['deps']
    cmds:
      - 'ansible-playbook --inventory {{.ANSIBLE_INVENTORY_FILE}} {{.ANSIBLE_DIR}}/playbooks/cluster-prepare.yaml'
      - 'ansible-playbook --inventory {{.ANSIBLE_INVENTORY_FILE}} {{.ANSIBLE_DIR}}/playbooks/cluster-installation.yaml'
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

  install-pihole:
    desc: Install Pi-hole
    summary: |
      Args:
        playbook: Playbook to run (required)
    prompt: Run Ansible playbook '{{.playbook}}'... continue?
    deps: ['deps']
    cmds:
      - 'ansible-playbook --inventory {{.ANSIBLE_INVENTORY_FILE}} {{.ANSIBLE_DIR}}/playbooks/pihole-install.yaml {{.CLI_ARGS}}'
    env:
      pihole_admin_password: '{{.pihole_admin_password}}'
      overwrite_setupvars: true
      pihole_adlists:
        - 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
        - 'https://mirror1.malwaredomains.com/files/justdomains'
        - 'http://sysctl.org/cameleon/hosts'
        - 'https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist'
        - 'https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt'
        - 'https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt'
        - 'https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt'
        - 'https://raw.githubusercontent.com/blocklistproject/Lists/master/abuse.txt'
        - 'https://raw.githubusercontent.com/blocklistproject/Lists/master/drugs.txt'
    requires:
      vars: ['pihole_admin_password']
    preconditions:
      - {
          msg: 'Missing Ansible inventory file',
          sh: 'test -f {{.ANSIBLE_INVENTORY_FILE}}',
        }

