schema: "https://www.krakend.io/schema/krakend.json"
version: 3,

# The name of the service
name: "Helix AI API Gateway"

# Timeout for the service
timeout: "3000ms"
cache_ttl: "300s"
output_encoding: "json"
echo_endpoint: false
sequential_start: true
debug_endpoint: true

extra_config:
  # Add Fluentd logging
  telemetry/logging:
    level: INFO
    syslog: false
    fluentd_address: "fluentd:24224"
    fluentd_tag: "krakend"

  # Add the Prometheus metrics exporter
  github_com/devopsfaith/krakend-metrics/prometheus:
    listen_address:  "prometheus:8081"
    endpoint: "/metrics"

endpoints:
  - endpoint: "/api/v1/health"
    method: "GET"
    output_encoding: "json"

  - endpoint: "/api/v1/health/elasticsearch"
    method: "GET"
    output_encoding: "json"
    extra_config:
      backend:
        encoding: "json"
        url_pattern: "http://elasticsearch:9200/_cluster/health"
        method: "GET"
        timeout: "3000ms"

  - endpoint: "/api/v1/health/consul"
    method: "GET"
    output_encoding: "json"
    extra_config:
      backend:
        encoding: "json"
        url_pattern: "http://consul-server-1:8500/v1/status/leader"
        method: "GET"
        timeout: "3000ms"

  - endpoint: "/api/v1/health/vault"
    method: "GET"
    output_encoding: "json"
    extra_config:
      backend:
        encoding: "json"
        url_pattern: "http://vault-server:8200/v1/sys/health"
        method: "GET"
        timeout: "3000ms"
