name: helix-ai-plartform

networks:
  consul:
    name: consul
    driver: bridge
  helix:
    name: helix
    driver: bridge

services:
  discord-bot:
    extends:
      file: ./apps.yaml
      service: discord-bot
  
  frontend:
    extends:
      file: ./apps.yaml
      service: frontend

  bootstrap:
    extends:
      file: ./bootstrap.yaml
      service: bootstrap

  flipt:
    extends:
      file: ./bootstrap.yaml
      service: flipt
  
  # consul-bootstrap:
  #   extends:
  #     file: ./consul.yaml
  #     service: consul-bootstrap
  
  # consul-1:
  #   extends:
  #     file: ./consul.yaml
  #     service: consul-server-1
  #   depends_on:
  #     consul-bootstrap:
  #       condition: service_completed_successfully
  #     vault-server:
  #       condition: service_healthy
  
  # consul-2:
  #   extends:
  #     file: ./consul.yaml
  #     service: consul-server-2
  #   depends_on:
  #     consul-bootstrap:
  #       condition: service_completed_successfully
  #     vault-server:
  #       condition: service_healthy
  #     consul-1:
  #       condition: service_healthy
  
  # consul-3:
  #   extends:
  #     file: ./consul.yaml
  #     service: consul-server-3
  #   depends_on:
  #     consul-bootstrap:
  #       condition: service_completed_successfully
  #     vault-server:
  #       condition: service_healthy
  #     consul-1:
  #       condition: service_healthy
  
  # consul-client:
  #   extends:
  #     file: ./consul.yaml
  #     service: consul-client
  #   depends_on:
  #     consul-bootstrap:
  #       condition: service_completed_successfully
  #     vault-server:
  #       condition: service_healthy
  
  # vault-server:
  #   extends:
  #     file: ./consul.yaml
  #     service: vault-server
  
  init-kafka-topics:
    extends:
      file: ./kafka.yaml
      service: init-kafka-topics
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
  
  kafka-0:
    extends:
      file: ./kafka.yaml
      service: kafka-0
  
  kafka-1:
    extends:
      file: ./kafka.yaml
      service: kafka-1
    depends_on:
      - kafka-0
  
  kafka-2:
    extends:
      file: ./kafka.yaml
      service: kafka-2
    depends_on:
      - kafka-0
      - kafka-1
  
  lavalink:
    extends:
      file: ./lavalink.yaml
      service: lavalink
  
  mysql:
    extends:
      file: ./mysql.yaml
      service: mysql
  
  redis:
    extends:
      file: ./redis.yaml
      service: redis
