version: '3.8'

networks:
  helix:
    external: true

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: redis
    hostname: redis
    restart: on-failure
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - helix
    volumes:
      - ../.data/redis:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
