services:
  vault:
    image: hashicorp/vault:1.17.1
    container_name: vault-server
    hostname: vault-server
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: 'http://vault-server:8200'
      VAULT_API_ADDR: 'http://vault-server:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      CONSUL_HTTP_ADDR: 'consul-server1:8500'
      CONSUL_HTTP_TOKEN: 'root'
      VAULT_STORAGE_MYSQL_USERNAME: 'helix_ai'
      VAULT_STORAGE_MYSQL_PASSWORD: 'zdqJ5zYmDEn1L07iAbBx'
      VAULT_STORAGE_MYSQL_ADDRESS: 'mysql:3306'
      VAULT_STORAGE_MYSQL_DATABASE: 'helix_ai'
      VAULT_STORAGE_MYSQL_TABLE: 'helix_vault'
    volumes:
      - ./vault/config/vault-server-1.hcl:/vault/config/server.hcl
      - ./vault/policies/policy.json:/vault/policies/policy.json
      - ./consul/generated/consul-certs/:/vault/certs/
      - ../.data/vault/logs:/vault/logs
      - ../.data/vault/data:/vault/data
    healthcheck:
      test: ['CMD', 'vault', 'status']
      interval: 10s
      timeout: 5s
      retries: 12
