services:
  consul-bootstrap: &consul-bootstrap
    build:
      context: ./setup
      dockerfile: ./Dockerfile
    container_name: consul-bootstrap
    hostname: consul-bootstrap
    volumes:
      - ./setup/config.yaml:/config/config.yaml
      - ./setup/scripts/consul/consul.sh:/home/docker/config/consul.sh
      - ./consul/generated:/consul/generated
      - ./consul/config:/consul/config
    command:
      - /bin/bash
      - /home/docker/config/consul.sh

  consul-server-1: &consul-server-1
    image: hashicorp/consul:1.17.1
    container_name: consul-server-1
    hostname: consul-server-1
    restart: always
    volumes:
      - ./consul/config/server-1:/consul/config
      - ./consul/generated/consul-certs/:/consul/config/certs/
      - ./certs/certificate_authority/certificate_authority.crt:/consul/config/certs/ca.pem
    command: 'agent'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8500/v1/status/leader']
      interval: 10s
      timeout: 5s
      retries: 12

  consul-server-2: &consul-server-2
    image: hashicorp/consul:1.17.1
    container_name: consul-server-2
    hostname: consul-server-2
    restart: always
    volumes:
      - ./consul/config/server-2:/consul/config
      - ./consul/generated/consul-certs/:/consul/config/certs/
      - ./certs/certificate_authority/certificate_authority.crt:/consul/config/certs/ca.pem
    command: 'agent'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8500/v1/status/leader']
      interval: 10s
      timeout: 5s
      retries: 12

  consul-server-3: &consul-server-3
    image: hashicorp/consul:1.17.1
    container_name: consul-server-3
    hostname: consul-server-3
    restart: always
    volumes:
      - ./consul/config/server-3:/consul/config
      - ./consul/generated/consul-certs/:/consul/config/certs/
      - ./certs/certificate_authority/certificate_authority.crt:/consul/config/certs/ca.pem
    command: 'agent'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8500/v1/status/leader']
      interval: 10s
      timeout: 5s
      retries: 12

  consul-client: &consul-client
    image: hashicorp/consul:1.17.1
    container_name: consul-client
    hostname: consul-client
    restart: always
    volumes:
      - ./consul/config/client-1:/consul/config
      - ./consul/generated/consul-intro-token-key:/consul/token
      - ./consul/generated/consul-certs/:/consul/config/certs/
    command: 'agent'


