export declare enum TechCategory {
    AI = 0,
    AR = 1,
    Analytics = 2,
    Backend = 3,
    Blockchain = 4,
    Cloud = 5,
    Containerization = 6,
    DNS = 7,
    Data = 8,
    Database = 9,
    Design = 10,
    Desktop = 11,
    DevOps = 12,
    Framework = 13,
    Frontend = 14,
    IoT = 15,
    Library = 16,
    Logging = 17,
    Management = 18,
    Mobile = 19,
    Other = 20,
    Productivity = 21,
    ProgramLanguage = 22,
    Security = 23,
    Testing = 24,
    VR = 25
}
