services:
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: sinless777/dev-container-node-python-go
    container_name: dev-container
    volumes:
      - '../../:/workspace'
      - './post-create-setup.sh:/home/node/post-create-setup.sh'
    command: tail -f /dev/null
    dns:
      - 1.1.1.1
      - 8.8.8.8
