#!/bin/zsh

# Define color codes
BLUE="\033[1;34m"
ORANGE="\033[0;33m"
RED="\033[1;31m"
BOLD_RED="\033[1;31m\033[1m"
RESET="\033[0m"

# Logging functions for info, warn, and error
log_info() {
  echo  "${BLUE}INFO:${RESET} $1"
}

log_warn() {
  echo "${ORANGE}WARN:${RESET} $1"
}

log_error() {
  echo "${BOLD_RED}ERROR:${RESET} $1"
}

log_info "Installing dependencies"
if npm install > /dev/null; then
  log_info "npm install completed successfully"
else
  log_error "npm install failed"
  exit 1
fi

log_info "Validateing renovate.json"
if npx --yes --package renovate -- renovate-config-validator --strict > /dev/null; then
  log_info "Renovate config validated successfully"
else
  log_error "Renovate config validation failed"
  exit 1
fi

