# GENERAL SETTINS

cluster.name:    "HelixAI"
node.name:       "helix-elasticsearch"
node.attr.zone:  "zone1"

node.data: true
node.master: true

network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1

http.port: 9200
transport.tcp.port: 9300

bootstrap.memory_lock: true

script.allowed_types: inline
