---
# this code belongs to onrdr0p
# https://github.com/onedr0p/flux-cluster-template/blob/main/.taskfiles/Kubernetes/Taskfile.yaml
#
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  KUBECONFORM_SCRIPT: '{{.TASKFILE_DIR}}/Kubernetes/kubeconform.sh'

tasks:
  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: resource }
        cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
      - {
          msg: 'Missing kubeconform script',
          sh: 'test -f {{.KUBECONFORM_SCRIPT}}',
        }
      - {
          msg: 'Missing kubernetes directory',
          sh: 'test -d {{.KUBERNETES_DIR}}',
        }
