services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      KAFKA_BROKER_CONNECT: kafka-1:9092,kafka-2:9093,kafka-3:9094
      KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    ports:
      - '32181:32181'
    volumes:
      - certificates_data:/etc/kafka/secrets/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-1
    ports:
      - '9092:9092'
    volumes:
      - certificates_data:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-2:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-2
    ports:
      - '9093:9093'
    volumes:
      - certificates_data:/etc/kafka/secrets/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-3:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-3
    ports:
      - '9094:9094'
    volumes:
      - certificates_data:/etc/kafka/secrets/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL,EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/data/keystores/kafka/kafka.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
