apiVersion: ENC[AES256_GCM,data:YfQ=,iv:8T0fHLZcR29gAAmNYCgn/vk8210WACrBCe0HLRPOwTg=,tag:cpWzDD+DsF6Qe+Ljs3MJbQ==,type:str]
kind: ENC[AES256_GCM,data:vfk/PBDS,iv:rxP9ss/FYupKhdPDZM8r9OiFwGHwSb+krkonSR2uFwg=,tag:rBITZuBI8prIYb/BYv9bwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2epfNbcmNr9+TyPBdTAvD29k,iv:8/E9O6/GjfTzKcSjdaHBkiQKosmeOGhKLKgouQrePSQ=,tag:w7d3iMY+8s9N/u3bwBoj1g==,type:str]
    namespace: ENC[AES256_GCM,data:g+RjYBkyGg==,iv:5JrKheRpRLwS5XC3Qqb5En8HhVpz7zahd/IPMXvqN80=,tag:A6P2X7YPHzIzX/JpO2DgLQ==,type:str]
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:a/EkfNI11ooD73KNpRMZ5DzxXfeubRRcKWzDOTGCNpcvVhAUcMk03kI5FxezkKS7nUMjGQ1drMfVI08bs0c83a3I5SgibSq63Qt0LmP+P4fXTbmgd8oFH7CNiQf5mJw=,iv:OCZuJ4cZKGAqHTJMdBBwZ2mHXmX8dJp4MRhwMaFfmmk=,tag:PGeQLUGirOzZDupALtX3RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pe3ytfj2scs5ekt34e9j3el25jp92cjdn4dugys3pg74rc3qctsxgwtkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VjNyZUdHYlo1Z1IxYVFU
            RXB2UzhZNUVaMG84SU00MGYra1JiM29ETDBZCmIrSEJ5UXRJYzRwd1U5UEtsMmpi
            c0UxWHp1MTRxcDRpMnowckVIMHIzQlkKLS0tIHRNVm9yQmRxN1VwNVl5RUlFVytW
            ckRGMHAxL2NRNno5bm82QVdJbk1FeDAKv7O43OhZVvnoSMn3bDC2p+zf+eYqiQLc
            HY9M+Pi+eHEiY6xGJ/xfnBgGpX7oVF/h6E4jDzFQjrIofhmDH9yyEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T15:52:23Z"
    mac: ENC[AES256_GCM,data:9hQZ2/NDInU2MZ0puVCzjV25kuGpaXCPK3SvBrCNxxAbgJ9WrbooArxrdSLCotkHcmLTGZNt8Ny+Q/+KSRq+JRPibxEMQydvKDl1P0/gcrjgVWFKCNhKmoMg1IUjhIyHwl8YkIV4PRJbuAwdDStsb2zB19M4sHwDzjoa8aubbaA=,iv:uzwHC1TAE1QfV9MHhREbdP/xsSpM7wKHzptVTmrUpio=,tag:gTpZNVeDpuZS5W0J4KQBIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
