# Kibana Configuration File

# Kibana server settings
server.name: 'helix-kibana'
server.host: '0.0.0.0'
server.port: 5601

# Set the basePath if you are running Kibana behind a reverse proxy or if you are hosting it under a subpath
# server.basePath: "/kibana"

# Elasticsearch settings
elasticsearch.hosts: ['https://elastic:9200']

# Security settings
elasticsearch.username: 'kibana'
elasticsearch.password: '${KIBANA_PASSWORD}' # Environment variable for Kibana user password

xpack.security.encryptionKey: "${ENCRYPTION_KEY}" # Environment variable for encryption key
xpack.encryptedSavedObjects.encryptionKey: "${ENCRYPTION_KEY}" # Environment variable for encryption key


# Enable TLS/SSL for secure communication between Kibana and Elasticsearch
elasticsearch.ssl.verificationMode: full
elasticsearch.ssl.certificateAuthorities: "/usr/share/kibana/config/certs/data/certificate_authority/certificate_authority.cert"

# Kibana's own TLS/SSL settings
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/data/certificates/kibana/kibana.pem
server.ssl.key: /usr/share/kibana/config/certs/data/certificates/kibana/kibana.key

# Authentication via OIDC (Auth0)
xpack.security.authc.providers:
  oidc.oidc1:
    order: 0
    realm: oidc1

# OIDC realm settings
xpack.security.authc.realms.oidc.oidc1:
  rp.client_id: "${AUTH0_CLIENT_ID}" # Environment variable for client ID
  rp.client_secret: "${AUTH0_CLIENT_SECRET}" # Environment variable for client secret
  rp.requested_scopes: [ "openid", "profile", "email" ]
  rp.redirect_uri: "https://localhost:5601/api/security/oidc/callback"
  op.issuer: "${AUTH0_ISSUER}" # Environment variable for Auth0 issuer (domain)
  op.authorization_endpoint: "${AUTH0_AUTHORIZATION_ENDPOINT}" # Environment variable for Auth0 authorization endpoint
  op.token_endpoint: "${AUTH0_TOKEN_ENDPOINT}" # Environment variable for Auth0 token endpoint
  op.jwkset_path: "${AUTH0_JWKSET_PATH}" # Environment variable for Auth0 JWKS endpoint
  claims.principal: sub
  claims.groups: roles
  rp.post_logout_redirect_uri: "https://localhost:5601/logout"

# Set a default index pattern (optional)
# kibana.defaultIndex: "logstash-*"

# Logging settings
logging.dest: /var/log/kibana/kibana.log
logging.quiet: false
logging.verbose: false

# X-Pack settings for security
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "${ENCRYPTION_KEY}" # Environment variable for encryption key

# Memory and performance tuning (optional)
server.maxPayloadBytes: 1048576 # Set max payload size for requests (optional)

logging:
  appenders:
    fluentd:
      type: socket
      protocol: tcp
      host: fluentd
      port: 24224
  root:
    appenders: [default, fluentd]

xpack.monitoring.collection.enabled: true
xpack.monitoring.ui.enabled: true
xpack.monitoring.kibana.collection.enabled: true

