declare namespace NodeJS {
  interface ProcessEnv {
    ADMIN_PASSWORD: string
    ADMIN_USERNAME: string
    API_FOLDER_ENABLED: string
    API_JWT_SECRET: string
    API_PORT: string
    APP_SPECIFIER: string
    AUTH0_AUDIENCE: string
    AUTH0_BASE_URL: string
    AUTH0_CLIENT_ID: string
    AUTH0_CLIENT_SECRET: string
    AUTH0_ISSUER_BASE_URL: string
    AUTH0_SCOPE: string
    AUTH0_SECRET: string
    AUTHOR_NAME: string
    CONFIG_VERSION: string
    CONSUL_HOST: string
    CONSUL_PORT: string
    CONSUL_Password: string
    CONSUL_URL: string
    CONSUL_USERNAME: string
    DEBUG: string
    DEBUG_LEVEL: string
    DISCORD_APPLICATION_ID: string
    DISCORD_BOT_DEFAULT_PREFIX: string
    DISCORD_BOT_INVITE_URL: string
    DISCORD_BOT_TOKEN: string
    DISCORD_CLIENT_ID: string
    DISCORD_CLIENT_SECRET: string
    DISCORD_DEVELOPER_IDS: string
    DISCORD_PUBLIC_KEY: string
    DISCORD_SUPPORT_SERVER_INVITE_URL: string
    DISCORD_TESTER_IDS: string
    ELASTICSEARCH_HOST: string
    ELASTICSEARCH_PASSWORD: string
    ELASTICSEARCH_PORT: string
    ELASTICSEARCH_USERNAME: string
    GITHUB_ID: string
    GITHUB_SECRET: string
    GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET
    KIBANA_HOST: string
    KIBANA_PASSWORD: string
    KIBANA_PORT: string
    KIBANA_USERNAME: string
    LAVALINK_SERVER_HOST: string
    LAVALINK_SERVER_PASSWORD: string
    LAVALINK_SERVER_PORT: string
    LOGSTASH_HOST: string
    LOGSTASH_PASSWORD: string
    LOGSTASH_PORT: string
    LOGSTASH_USERNAME: string
    LOG_FILE: string
    LOG_TO_CONSOLE: string
    LOG_TO_FILE: string
    MODE: string
    MONGODB_DB_NAME: string
    MONGODB_HOST: string
    MONGODB_PASSWORD: string
    MONGODB_PORT: string
    MONGODB_USER: string
    MYSQL_DATABASE: string
    MYSQL_DATABASE_URL: string
    MYSQL_HOST: string
    MYSQL_PASSWORD: string
    MYSQL_PORT: string
    MYSQL_USER: string
    NEXTAUTH_SECRET: string
    NEXTAUTH_URL: string
    OAUTH2_REDIRECT_URL: string
    OPENAI_API_KEY: string
    OPENAI_ORG_ID: string
    RABBITMQ_HOST: string
    RABBITMQ_PASSWORD: string
    RABBITMQ_PORT: string
    RABBITMQ_USERNAME: string
    REDIS_HOST: string
    REDIS_PASSWORD: string
    REDIS_PORT: string
    REDIS_USERNAME: string
    SPOTIFY_CLIENT_ID: string
    SPOTIFY_CLIENT_SEcRET: string
    TIMEZONE: string
    TWITCH_CLIENT_ID: string
    TWITCH_CLIENT_SECRET: string
    VERSION: string
  }
}
