services:
  vault:
    image: hashicorp/vault:1.17.1
    container_name: vault-server
    hostname: vault-server
    cap_add:
      - IPC_LOCK
    environment:
      # Vault addresses
      VAULT_ADDR: 'http://vault-server:8200'
      VAULT_API_ADDR: 'http://vault-server:8200'
      # Vault root token for development (replace in production)
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      # Consul configuration for service discovery
      CONSUL_HTTP_ADDR: "${CONSUL_HTTP_ADDR:-consul-server-1:8500}"       # Default to consul-server-1:8500
      CONSUL_HTTP_TOKEN: "${CONSUL_HTTP_TOKEN:-root}"                     # Default to root token
      # Consul certificates
      VAULT_CONSUL_CA_FILE: "${VAULT_CONSUL_CA_FILE:-/vault/config/certs/data/certificate_authority/certificate_authorities.crt}"
      VAULT_CONSUL_CERT_FILE: "${VAULT_CONSUL_CERT_FILE:-/vault/config/certs/data/certificates/consul/consul.crt}"
      VAULT_CONSUL_KEY_FILE: "${VAULT_CONSUL_KEY_FILE:-/vault/config/certs/data/certificates/consul/consul.key}"
      # Vault TLS certificates
      VAULT_TLS_CERT_FILE: "${VAULT_TLS_CERT_FILE:-/vault/config/certs/data/certificates/vault/vault.pem}"
      VAULT_TLS_KEY_FILE: "${VAULT_TLS_KEY_FILE:-/vault/config/certs/data/certificates/vault/vault.key}"
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_ISSUER: ${AUTH0_ISSUER}
      AUTH0_AUTHORIZATION_ENDPOINT: ${AUTH0_AUTHORIZATION_ENDPOINT}
      AUTH0_JWKSET_PATH: ${AUTH0_JWKSET_PATH}
    volumes:
      # Configuration files
      - ./vault/config/vault-server-1.hcl:/vault/config/server.hcl
      - ./vault/config/oidc-auth.hcl:/vault/config/oidc-auth.hcl
      # Policy files
      - ./vault/policies/policy.json:/vault/policies/policy.json
      # Persistent data volume
      - vault_data:/vault/data
