#!/bin/zsh

# Define color codes
BLUE="\033[1;34m"
ORANGE="\033[0;33m"
RED="\033[1;31m"
BOLD_RED="\033[1;31m\033[1m"
RESET="\033[0m"

# Logging functions for info, warn, and error
log_info() {
  echo  "${BLUE}INFO:${RESET} $1"
}

log_warn() {
  echo "${ORANGE}WARN:${RESET} $1"
}

log_error() {
  echo "${BOLD_RED}ERROR:${RESET} $1"
}

# Run Lint staged
if npx lint-staged; then
  log_info "Running lint-staged"
else
  log_error "lint-staged failed"
  exit 1
fi


output=$(npx --no-install commitlint --edit "$1" 2>&1 | tee /dev/tty)
if [ $? -eq 0 ]; then
  log_info "commitlint completed successfully"
else
  log_error "commitlint failed with the following output:"
  echo "$output"
  exit 1
fi
