#!/bin/zsh

printf '######################################'
printf '\n Run commit_msg \n'
printf '######################################'

#
# Run lint-staged with husky
printf '######################################'
printf 'Running lint-staged'
lint-staged
printf 'Completed lint-staged'

#
# run Commitlint with husky
printf 'Running commitlint'
npx --no-install commitlint --edit $1
printf 'Completed commitlint '
printf '######################################'

printf '######################################'
printf 'Completed commit_msg \n'
printf '######################################'
