#!/bin/zsh

printf '\n\n######################################'
printf '\n Run commit_msg \n'
printf '######################################\n\n'

#
# Run lint-staged with husky
printf '######################################\n'
printf 'Running lint-staged \n'
lint-staged
printf 'Completed lint-staged \n'

#
# run Commitlint with husky
printf 'Running commitlint \n'
npx --no-install commitlint --edit $1
printf 'Completed commitlint \n'
printf '######################################\n\n'

printf '\n\n######################################'
printf '\n Completed commit_msg \n'
printf '######################################\n\n'
