#!/bin/zsh

printf '\n\n######################################'
printf "\nRunning precommmit hook\n"
printf '######################################\n\n'

# Install dependencies
printf '######################################\n'
printf "Installing dependencies\n"

npm install
printf '######################################\n\n'

printf '######################################'
printf "\n\nCompleted Precommit\n\n"
printf '######################################\n\n'
