#!/bin/zsh

printf '######################################'
printf "\nRunning precommmit hook\n"
printf '######################################'

# Install dependencies
printf '######################################'
printf "Installing dependencies"

npm install
printf '######################################'

printf '######################################'
printf "\n\nCompleted Precommit\n\n"
printf '######################################'
