---
name: 'Kubeconform'

on:
  pull_request:
    branches: ['master']
    paths: ['kubernetes/**']

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux kubeconform kustomize

      - name: Run kubeconform
        shell: bash
        run: ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
