name: Labeler

on:
  workflow_dispatch:
  pull_request_target:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 6 PM UTC

env:
  PR_EXISTS: false

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ${{ github.repository }}

      - name: Check if Pull Request exists
        id: pr_exists
        run: |
          if [ "${{ github.event.pull_request }}" != "" ]; then
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          else
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Run Labeler
        # if: env.PR_EXISTS == 'false'
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: true
