name: Nx CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # this is needed if our pipeline publishes to npm

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - run: npm install @nx/nx-linux-x64-gnu --force
      - run: npm ci

      - run: git track master origin/master
      - uses: nrwl/nx-set-shas@v3

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected --base origin/master --head ${{ github.sha }} -t lint test build # e2e-ci
