name: Nx CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # this is needed if our pipeline publishes to npm

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"
      - run: npm install @nx/nx-linux-x64-gnu --force
      - run: npm ci

      - uses: nrwl/nx-set-shas@v3

      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track master origin/master

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected --base origin/master -t lint test build # e2e-ci
