name: NX Workflow

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_BASE_BRANCH: ${{ github.base_ref }}
  NX_HEAD: ${{ github.sha }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Setup python 3.12
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: npm install
      - run: npx nx run helix:install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "master"

      - run: |
          echo "BASE: ${{ steps.setSHAs.outputs.base }}"
          echo "HEAD: ${{ steps.setSHAs.outputs.head }}"

      - run: npx nx-cloud record -- nx run-many -t format:check --all
      - run: npx nx run-many -t lint test --all
