name: NX Workflow

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # CHeck What is being used for --base4
      - run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      # Check if there are changes between the base and the head
      - run: git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "apps" && echo "apps changed" || echo "apps not changed"

      # Set NX_BASE and NX_HEAD
      - run: echo "NX_BASE=${{ github.event.before }}" >> $GITHUB_ENV
      - run: echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t lint test build
