name: pr-review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  review:
    name: ChatGPT code review
    runs-on: ubuntu-latest
    steps:
      - uses: agogear/chatgpt-pr-review@0.0.11
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}

      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: New PR opened
          message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub PR Notifier
