name: Create Pull Request

on:
  # Schedule to run daily at 2am
  schedule:
    - cron: '0 2 * * *'

  # Trigger the workflow on push to the specified branches
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.1

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g commitlint

      - name: Validate commit messages with commitlint
        run: |
          git log --format=%B $(git rev-parse HEAD)~1..HEAD | commitlint
        continue-on-error: true # Allows the workflow to continue even if commitlint fails

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }} # Use the current branch
          base: develop # Assuming you want to merge into develop
          title: '🤖⚙️ Automated PR: Update from ${{ github.ref_name }} ⚙️🤖' # Use emojis to make it fun! 🚀
          body: 'This is an automated PR created for the branch ${{ github.ref_name }}.'
          labels: 'automated, dependencies'

      - name: Notify if commitlint failed
        if: failure() && steps.create_pr.outcome == 'skipped'
        run: echo "Commitlint failed or PR already exists, skipping PR creation."
