import './global.css'
import { StyledComponentsRegistry } from './registry'
import { ConfigCatProvider } from 'configcat-react'

export const metadata = {
  title: 'Welcome to Helix Ai',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ConfigCatProvider sdkKey="configcat-sdk-1/hWXcCIX7VkiGMmG_HAtV4Q/cdpGecK0AEqHukM6Jz7TIQ">
            {children}
          </ConfigCatProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
